version: "3"
services:
  muh_postgres_db:
    image: postgres
    container_name: muh_postgres_db
    volumes:
      - muh_postgres_db_volume:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_HOST_AUTH_METHOD: 'trust'
    ports:
      - '5444:5432'

  muh_rails_server:
    image: edimossilva/muh_rails_server:latest
    container_name: muh_rails_server
    volumes:
      - ./backend:/app
    depends_on:
      - muh_postgres_db
    environment:
      RAILS_MASTER_KEY: 'a667717bf0a47475b0582547379c816d'
      DATABASE_USERNAME: 'postgres'
      DATABASE_PASSWORD: 'postgres'
      DATABASE_HOST: 'muh_postgres_db'
      DATABASE_PORT: '5432'
      DATABASE_NAME: 'muh_db'
      JWT_SECRET_KEY: 'super_secret'
    tty: true
    ports:
      - "3000:3000"
    entrypoint: /app/scripts/configure_database.sh


  muh_android:
    image: semaphoreci/android:29
    container_name: muh_android
    working_dir: /app
    volumes:
      - ./android:/app
    tty: true
    command: sh

volumes:
  muh_postgres_db_volume:
# docker-compose build
# docker-compose up -d
# docker-compose exec muh_rails_server rspec
# docker build -f Dockerfile_rails . -t edimossilva/muh_rails_server
# docker push edimossilva/muh_rails_server
